In [2]:
from __future__ import absolute_import, division, print_function, unicode_literals

try:
  %tensorflow_version 2.x
except Exception:
  pass

import tensorflow as tf

TensorFlow 2.x selected.


In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


11493376/11490434 [==============================] - 0s 0us/step


In [0]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)                                    
])

In [6]:
predictions = model(x_train[:1]).numpy()
predictions


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



array([[ 0.04278743,  0.1959073 , -0.06742467,  0.01775265,  0.5876297 ,
        -0.08736669, -0.2075164 , -0.1809849 ,  0.08273757,  0.12642309]],
      dtype=float32)

In [0]:
x_train

In [0]:
y_train

In [9]:
tf.nn.softmax(predictions).numpy()

array([[0.09666754, 0.1126626 , 0.08657971, 0.09427752, 0.16668734,
        0.08487023, 0.07526188, 0.07728541, 0.1006076 , 0.1051001 ]],
      dtype=float32)

In [0]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [11]:
loss_fn(y_train[:1], predictions).numpy()

2.466632

In [0]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [14]:
model.fit(x_train, y_train, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 5s 91us/sample - loss: 0.3001 - accuracy: 0.9130
Epoch 2/5
60000/60000 [==============================] - 5s 84us/sample - loss: 0.1441 - accuracy: 0.9570
Epoch 3/5
60000/60000 [==============================] - 5s 85us/sample - loss: 0.1079 - accuracy: 0.9674
Epoch 4/5
60000/60000 [==============================] - 5s 89us/sample - loss: 0.0898 - accuracy: 0.9718
Epoch 5/5
60000/60000 [==============================] - 5s 89us/sample - loss: 0.0740 - accuracy: 0.9765


In [15]:
model.evaluate(x_test, y_test, verbose=2)

10000/10000 - 1s - loss: 0.0800 - accuracy: 0.9753


[0.08004017190844752, 0.9753]

In [0]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()                                         
])

In [18]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.5363851e-08, 2.5391248e-08, 3.4561913e-06, 6.6708139e-06,
        2.6068465e-11, 7.1593661e-08, 2.5475008e-13, 9.9998832e-01,
        3.4286867e-08, 1.3802285e-06],
       [9.8293029e-10, 1.2632138e-04, 9.9985635e-01, 1.7280521e-05,
        2.3451621e-13, 1.4959516e-08, 1.6769329e-09, 1.5924784e-11,
        4.3241574e-08, 1.6667404e-14],
       [3.3794839e-07, 9.9904090e-01, 6.6642111e-05, 5.7299521e-06,
        2.9275825e-05, 3.7781692e-06, 3.1738157e-06, 7.9410238e-04,
        5.5725501e-05, 1.9914347e-07],
       [9.9999225e-01, 1.7471242e-09, 6.8082645e-06, 3.0561855e-09,
        2.2549946e-09, 1.6687449e-07, 1.1879362e-07, 7.1255857e-07,
        3.2906088e-11, 5.9373395e-08],
       [1.8516049e-06, 3.6393370e-08, 1.6123839e-04, 6.1248791e-08,
        9.9794632e-01, 5.0420908e-08, 3.7295256e-05, 1.0488621e-04,
        8.5490221e-08, 1.7481319e-03]], dtype=float32)>

In [0]:
import numpy as np

In [22]:
data = np.random.random((1000, 32))
labels = np.random.random((1000, 10))

val_data = np.random.random((100, 32))
val_labels = np.random.random((100, 10))
val_labels
#model.fit(data, labels, epochs = 10, batch_size = 32,
#          validation_data=(val_data, val_labels))

array([[1.41403044e-02, 8.98886736e-02, 2.73487598e-02, 3.78272517e-01,
        7.76439775e-01, 9.49736151e-01, 8.05400829e-01, 7.91517577e-01,
        6.23882771e-01, 4.32507421e-01],
       [6.84533630e-01, 4.58190905e-01, 7.51175898e-01, 3.45218501e-01,
        1.01927146e-01, 4.98006774e-01, 9.05333891e-01, 4.75825297e-01,
        1.21520028e-01, 9.90200422e-01],
       [2.10679143e-01, 2.08217877e-01, 9.32911622e-01, 9.88119430e-01,
        2.52491397e-01, 3.48329935e-01, 3.57047825e-01, 4.19719208e-01,
        4.32391019e-01, 6.41343828e-01],
       [4.21846340e-01, 4.55420942e-01, 6.43572781e-02, 7.26815344e-01,
        7.17396539e-02, 3.37311947e-01, 4.40786497e-02, 6.60579467e-01,
        8.95501261e-01, 4.92667276e-01],
       [4.88894044e-01, 9.62691936e-01, 2.20891985e-01, 1.61431486e-01,
        2.03653084e-01, 9.87142872e-01, 4.31178198e-01, 9.70395151e-01,
        4.05683846e-01, 3.17954034e-01],
       [8.36188959e-02, 8.05300027e-01, 7.36543464e-01, 8.97655838e-02,
   